version: "3.2"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=reservatron
      - POSTGRES_USER=reservatron
      - POSTGRES_DB=reservatron
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
  reservatron:
    image: tabler/reservatron
    ports:
      - "8080:8080"
    links:
      - redis
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
  admin:
    image: tabler/admin
    ports:
      - "8081:8080"
    links:
      - postgres
    environment:
      - POSTGRES_HOST=postgres